// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace File_Manager.Entities;

public partial class Department
{
    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<DepartmentFile> DepartmentFiles { get; set; } = new List<DepartmentFile>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}
