// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace File_Manager.Entities;

public partial class FileType
{
    public int FileTypeId { get; set; }

    public string FileTypeName { get; set; }

    public virtual ICollection<File> Files { get; set; } = new List<File>();
}